/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectionType: typeof import('./src/components/inputs/CollectionType.vue')['default']
    DynamicTags: typeof import('./src/components/DynamicTags.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    MoreOptions: typeof import('./src/components/MoreOptions.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Range: typeof import('./src/components/inputs/Range.vue')['default']
    Reqeust: typeof import('./src/components/Reqeust.vue')['default']
    Request: typeof import('./src/components/Request.vue')['default']
    Select: typeof import('./src/components/inputs/Select.vue')['default']
    Tag: typeof import('./src/components/inputs/Tag.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    Transition: typeof import('./src/components/Transition.vue')['default']
    UserID: typeof import('./src/components/inputs/UserID.vue')['default']
  }
}
