// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CatalogCastPositionV1RoleScope.
const (
	All  CatalogCastPositionV1RoleScope = "all"
	Main CatalogCastPositionV1RoleScope = "main"
)

// Valid indicates whether the value is a known member of the CatalogCastPositionV1RoleScope enum.
func (e CatalogCastPositionV1RoleScope) Valid() bool {
	switch e {
	case All:
		return true
	case Main:
		return true
	default:
		return false
	}
}

// Defines values for CatalogCastPositionV1Status.
const (
	CatalogCastPositionV1StatusHidden     CatalogCastPositionV1Status = "hidden"
	CatalogCastPositionV1StatusSelectable CatalogCastPositionV1Status = "selectable"
)

// Valid indicates whether the value is a known member of the CatalogCastPositionV1Status enum.
func (e CatalogCastPositionV1Status) Valid() bool {
	switch e {
	case CatalogCastPositionV1StatusHidden:
		return true
	case CatalogCastPositionV1StatusSelectable:
		return true
	default:
		return false
	}
}

// Defines values for CatalogFilterCapabilityV1Field.
const (
	CatalogFilterCapabilityV1FieldCollectionUpdatedAt CatalogFilterCapabilityV1Field = "collectionUpdatedAt"
	CatalogFilterCapabilityV1FieldGlobalScore         CatalogFilterCapabilityV1Field = "globalScore"
	CatalogFilterCapabilityV1FieldIncludeNSFW         CatalogFilterCapabilityV1Field = "includeNSFW"
	CatalogFilterCapabilityV1FieldMergeSeries         CatalogFilterCapabilityV1Field = "mergeSeries"
	CatalogFilterCapabilityV1FieldPersonalScore       CatalogFilterCapabilityV1Field = "personalScore"
	CatalogFilterCapabilityV1FieldRatingCount         CatalogFilterCapabilityV1Field = "ratingCount"
	CatalogFilterCapabilityV1FieldScoreDifference     CatalogFilterCapabilityV1Field = "scoreDifference"
	CatalogFilterCapabilityV1FieldSubjectDate         CatalogFilterCapabilityV1Field = "subjectDate"
	CatalogFilterCapabilityV1FieldTags                CatalogFilterCapabilityV1Field = "tags"
)

// Valid indicates whether the value is a known member of the CatalogFilterCapabilityV1Field enum.
func (e CatalogFilterCapabilityV1Field) Valid() bool {
	switch e {
	case CatalogFilterCapabilityV1FieldCollectionUpdatedAt:
		return true
	case CatalogFilterCapabilityV1FieldGlobalScore:
		return true
	case CatalogFilterCapabilityV1FieldIncludeNSFW:
		return true
	case CatalogFilterCapabilityV1FieldMergeSeries:
		return true
	case CatalogFilterCapabilityV1FieldPersonalScore:
		return true
	case CatalogFilterCapabilityV1FieldRatingCount:
		return true
	case CatalogFilterCapabilityV1FieldScoreDifference:
		return true
	case CatalogFilterCapabilityV1FieldSubjectDate:
		return true
	case CatalogFilterCapabilityV1FieldTags:
		return true
	default:
		return false
	}
}

// Defines values for CatalogGroupV1Kind.
const (
	Bangumi  CatalogGroupV1Kind = "bangumi"
	Custom   CatalogGroupV1Kind = "custom"
	Fallback CatalogGroupV1Kind = "fallback"
	Shortcut CatalogGroupV1Kind = "shortcut"
)

// Valid indicates whether the value is a known member of the CatalogGroupV1Kind enum.
func (e CatalogGroupV1Kind) Valid() bool {
	switch e {
	case Bangumi:
		return true
	case Custom:
		return true
	case Fallback:
		return true
	case Shortcut:
		return true
	default:
		return false
	}
}

// Defines values for CatalogOperationApplicabilityV10Operation.
const (
	CatalogOperationApplicabilityV10OperationCandidates CatalogOperationApplicabilityV10Operation = "candidates"
	CatalogOperationApplicabilityV10OperationCoStar     CatalogOperationApplicabilityV10Operation = "coStar"
	CatalogOperationApplicabilityV10OperationPartners   CatalogOperationApplicabilityV10Operation = "partners"
	CatalogOperationApplicabilityV10OperationRankings   CatalogOperationApplicabilityV10Operation = "rankings"
)

// Valid indicates whether the value is a known member of the CatalogOperationApplicabilityV10Operation enum.
func (e CatalogOperationApplicabilityV10Operation) Valid() bool {
	switch e {
	case CatalogOperationApplicabilityV10OperationCandidates:
		return true
	case CatalogOperationApplicabilityV10OperationCoStar:
		return true
	case CatalogOperationApplicabilityV10OperationPartners:
		return true
	case CatalogOperationApplicabilityV10OperationRankings:
		return true
	default:
		return false
	}
}

// Defines values for CatalogPositionCapabilityNameV1.
const (
	CatalogPositionCapabilityNameV1Candidates   CatalogPositionCapabilityNameV1 = "candidates"
	CatalogPositionCapabilityNameV1CoStar       CatalogPositionCapabilityNameV1 = "coStar"
	CatalogPositionCapabilityNameV1Partners     CatalogPositionCapabilityNameV1 = "partners"
	CatalogPositionCapabilityNameV1PersonDetail CatalogPositionCapabilityNameV1 = "personDetail"
	CatalogPositionCapabilityNameV1Rankings     CatalogPositionCapabilityNameV1 = "rankings"
)

// Valid indicates whether the value is a known member of the CatalogPositionCapabilityNameV1 enum.
func (e CatalogPositionCapabilityNameV1) Valid() bool {
	switch e {
	case CatalogPositionCapabilityNameV1Candidates:
		return true
	case CatalogPositionCapabilityNameV1CoStar:
		return true
	case CatalogPositionCapabilityNameV1Partners:
		return true
	case CatalogPositionCapabilityNameV1PersonDetail:
		return true
	case CatalogPositionCapabilityNameV1Rankings:
		return true
	default:
		return false
	}
}

// Defines values for CatalogRootSortCapabilityV1Field.
const (
	CatalogRootSortCapabilityV1FieldAverage             CatalogRootSortCapabilityV1Field = "average"
	CatalogRootSortCapabilityV1FieldCollectionUpdatedAt CatalogRootSortCapabilityV1Field = "collectionUpdatedAt"
	CatalogRootSortCapabilityV1FieldCount               CatalogRootSortCapabilityV1Field = "count"
	CatalogRootSortCapabilityV1FieldGlobalAverage       CatalogRootSortCapabilityV1Field = "globalAverage"
	CatalogRootSortCapabilityV1FieldGlobalScore         CatalogRootSortCapabilityV1Field = "globalScore"
	CatalogRootSortCapabilityV1FieldName                CatalogRootSortCapabilityV1Field = "name"
	CatalogRootSortCapabilityV1FieldOverall             CatalogRootSortCapabilityV1Field = "overall"
	CatalogRootSortCapabilityV1FieldPersonalScore       CatalogRootSortCapabilityV1Field = "personalScore"
	CatalogRootSortCapabilityV1FieldPreference          CatalogRootSortCapabilityV1Field = "preference"
	CatalogRootSortCapabilityV1FieldRole                CatalogRootSortCapabilityV1Field = "role"
	CatalogRootSortCapabilityV1FieldSeriesSize          CatalogRootSortCapabilityV1Field = "seriesSize"
	CatalogRootSortCapabilityV1FieldWorkCount           CatalogRootSortCapabilityV1Field = "workCount"
)

// Valid indicates whether the value is a known member of the CatalogRootSortCapabilityV1Field enum.
func (e CatalogRootSortCapabilityV1Field) Valid() bool {
	switch e {
	case CatalogRootSortCapabilityV1FieldAverage:
		return true
	case CatalogRootSortCapabilityV1FieldCollectionUpdatedAt:
		return true
	case CatalogRootSortCapabilityV1FieldCount:
		return true
	case CatalogRootSortCapabilityV1FieldGlobalAverage:
		return true
	case CatalogRootSortCapabilityV1FieldGlobalScore:
		return true
	case CatalogRootSortCapabilityV1FieldName:
		return true
	case CatalogRootSortCapabilityV1FieldOverall:
		return true
	case CatalogRootSortCapabilityV1FieldPersonalScore:
		return true
	case CatalogRootSortCapabilityV1FieldPreference:
		return true
	case CatalogRootSortCapabilityV1FieldRole:
		return true
	case CatalogRootSortCapabilityV1FieldSeriesSize:
		return true
	case CatalogRootSortCapabilityV1FieldWorkCount:
		return true
	default:
		return false
	}
}

// Defines values for CatalogRootSortCapabilityV1Operation.
const (
	CatalogRootSortCapabilityV1OperationCandidates CatalogRootSortCapabilityV1Operation = "candidates"
	CatalogRootSortCapabilityV1OperationCoStar     CatalogRootSortCapabilityV1Operation = "coStar"
	CatalogRootSortCapabilityV1OperationPartners   CatalogRootSortCapabilityV1Operation = "partners"
	CatalogRootSortCapabilityV1OperationRankings   CatalogRootSortCapabilityV1Operation = "rankings"
)

// Valid indicates whether the value is a known member of the CatalogRootSortCapabilityV1Operation enum.
func (e CatalogRootSortCapabilityV1Operation) Valid() bool {
	switch e {
	case CatalogRootSortCapabilityV1OperationCandidates:
		return true
	case CatalogRootSortCapabilityV1OperationCoStar:
		return true
	case CatalogRootSortCapabilityV1OperationPartners:
		return true
	case CatalogRootSortCapabilityV1OperationRankings:
		return true
	default:
		return false
	}
}

// Defines values for CatalogScopeV1.
const (
	Global   CatalogScopeV1 = "global"
	Personal CatalogScopeV1 = "personal"
)

// Valid indicates whether the value is a known member of the CatalogScopeV1 enum.
func (e CatalogScopeV1) Valid() bool {
	switch e {
	case Global:
		return true
	case Personal:
		return true
	default:
		return false
	}
}

// Defines values for CatalogSectionSortCapabilityV1Field.
const (
	CatalogSectionSortCapabilityV1FieldCollectionUpdatedAt CatalogSectionSortCapabilityV1Field = "collectionUpdatedAt"
	CatalogSectionSortCapabilityV1FieldGlobalScore         CatalogSectionSortCapabilityV1Field = "globalScore"
	CatalogSectionSortCapabilityV1FieldName                CatalogSectionSortCapabilityV1Field = "name"
	CatalogSectionSortCapabilityV1FieldPersonalScore       CatalogSectionSortCapabilityV1Field = "personalScore"
	CatalogSectionSortCapabilityV1FieldRole                CatalogSectionSortCapabilityV1Field = "role"
	CatalogSectionSortCapabilityV1FieldSeriesSize          CatalogSectionSortCapabilityV1Field = "seriesSize"
	CatalogSectionSortCapabilityV1FieldWorkCount           CatalogSectionSortCapabilityV1Field = "workCount"
)

// Valid indicates whether the value is a known member of the CatalogSectionSortCapabilityV1Field enum.
func (e CatalogSectionSortCapabilityV1Field) Valid() bool {
	switch e {
	case CatalogSectionSortCapabilityV1FieldCollectionUpdatedAt:
		return true
	case CatalogSectionSortCapabilityV1FieldGlobalScore:
		return true
	case CatalogSectionSortCapabilityV1FieldName:
		return true
	case CatalogSectionSortCapabilityV1FieldPersonalScore:
		return true
	case CatalogSectionSortCapabilityV1FieldRole:
		return true
	case CatalogSectionSortCapabilityV1FieldSeriesSize:
		return true
	case CatalogSectionSortCapabilityV1FieldWorkCount:
		return true
	default:
		return false
	}
}

// Defines values for CatalogSectionV1.
const (
	Characters CatalogSectionV1 = "characters"
	Works      CatalogSectionV1 = "works"
)

// Valid indicates whether the value is a known member of the CatalogSectionV1 enum.
func (e CatalogSectionV1) Valid() bool {
	switch e {
	case Characters:
		return true
	case Works:
		return true
	default:
		return false
	}
}

// Defines values for CatalogSelectionRuleV1Kind.
const (
	ExactCast     CatalogSelectionRuleV1Kind = "exactCast"
	ExactStaff    CatalogSelectionRuleV1Kind = "exactStaff"
	StaffSetUnion CatalogSelectionRuleV1Kind = "staffSetUnion"
)

// Valid indicates whether the value is a known member of the CatalogSelectionRuleV1Kind enum.
func (e CatalogSelectionRuleV1Kind) Valid() bool {
	switch e {
	case ExactCast:
		return true
	case ExactStaff:
		return true
	case StaffSetUnion:
		return true
	default:
		return false
	}
}

// Defines values for CatalogStaffPositionV1Status.
const (
	CatalogStaffPositionV1StatusHidden     CatalogStaffPositionV1Status = "hidden"
	CatalogStaffPositionV1StatusSelectable CatalogStaffPositionV1Status = "selectable"
)

// Valid indicates whether the value is a known member of the CatalogStaffPositionV1Status enum.
func (e CatalogStaffPositionV1Status) Valid() bool {
	switch e {
	case CatalogStaffPositionV1StatusHidden:
		return true
	case CatalogStaffPositionV1StatusSelectable:
		return true
	default:
		return false
	}
}

// Defines values for CatalogStaffSetPositionV1Status.
const (
	CatalogStaffSetPositionV1StatusHidden     CatalogStaffSetPositionV1Status = "hidden"
	CatalogStaffSetPositionV1StatusSelectable CatalogStaffSetPositionV1Status = "selectable"
)

// Valid indicates whether the value is a known member of the CatalogStaffSetPositionV1Status enum.
func (e CatalogStaffSetPositionV1Status) Valid() bool {
	switch e {
	case CatalogStaffSetPositionV1StatusHidden:
		return true
	case CatalogStaffSetPositionV1StatusSelectable:
		return true
	default:
		return false
	}
}

// Defines values for CatalogSubjectTypeKeyV1.
const (
	Anime CatalogSubjectTypeKeyV1 = "anime"
	Book  CatalogSubjectTypeKeyV1 = "book"
	Game  CatalogSubjectTypeKeyV1 = "game"
	Music CatalogSubjectTypeKeyV1 = "music"
	Real  CatalogSubjectTypeKeyV1 = "real"
)

// Valid indicates whether the value is a known member of the CatalogSubjectTypeKeyV1 enum.
func (e CatalogSubjectTypeKeyV1) Valid() bool {
	switch e {
	case Anime:
		return true
	case Book:
		return true
	case Game:
		return true
	case Music:
		return true
	case Real:
		return true
	default:
		return false
	}
}

// CatalogCastPositionV1 defines model for CatalogCastPositionV1.
type CatalogCastPositionV1 struct {
	Capabilities   []CatalogPositionCapabilityNameV1 `json:"capabilities"`
	Categories     []string                          `json:"categories"`
	DisplayOrder   int                               `json:"displayOrder"`
	ExclusiveGroup string                            `json:"exclusiveGroup"`
	Key            string                            `json:"key"`
	Kind           interface{}                       `json:"kind"`
	Label          string                            `json:"label"`
	Names          CatalogLocalizedNamesV1           `json:"names"`
	RoleScope      CatalogCastPositionV1RoleScope    `json:"roleScope"`
	Status         CatalogCastPositionV1Status       `json:"status"`
	SubjectType    CatalogSubjectTypeKeyV1           `json:"subjectType"`
}

// CatalogCastPositionV1RoleScope defines model for CatalogCastPositionV1.RoleScope.
type CatalogCastPositionV1RoleScope string

// CatalogCastPositionV1Status defines model for CatalogCastPositionV1.Status.
type CatalogCastPositionV1Status string

// CatalogDataV1 defines model for CatalogDataV1.
type CatalogDataV1 struct {
	FilterCapabilities []CatalogFilterCapabilityV1 `json:"filterCapabilities"`
	Groups             []CatalogGroupV1            `json:"groups"`
	Positions          []CatalogPositionV1         `json:"positions"`
	SelectionRules     []CatalogSelectionRuleV1    `json:"selectionRules"`
	SortCapabilities   []CatalogSortCapabilityV1   `json:"sortCapabilities"`
	SubjectTypes       []CatalogSubjectTypeV1      `json:"subjectTypes"`
}

// CatalogFilterCapabilityV1 defines model for CatalogFilterCapabilityV1.
type CatalogFilterCapabilityV1 struct {
	Applications []CatalogOperationApplicabilityV1 `json:"applications"`
	Field        CatalogFilterCapabilityV1Field    `json:"field"`
	Scopes       []CatalogScopeV1                  `json:"scopes"`
	SubjectTypes []CatalogSubjectTypeKeyV1         `json:"subjectTypes"`
}

// CatalogFilterCapabilityV1Field defines model for CatalogFilterCapabilityV1.Field.
type CatalogFilterCapabilityV1Field string

// CatalogGroupV1 defines model for CatalogGroupV1.
type CatalogGroupV1 struct {
	DisplayOrder int                     `json:"displayOrder"`
	Key          string                  `json:"key"`
	Kind         CatalogGroupV1Kind      `json:"kind"`
	Label        string                  `json:"label"`
	PositionKeys []string                `json:"positionKeys"`
	SubjectType  CatalogSubjectTypeKeyV1 `json:"subjectType"`
}

// CatalogGroupV1Kind defines model for CatalogGroupV1.Kind.
type CatalogGroupV1Kind string

// CatalogLocalizedNamesV1 defines model for CatalogLocalizedNamesV1.
type CatalogLocalizedNamesV1 struct {
	Cn string  `json:"cn"`
	En *string `json:"en"`
	Jp *string `json:"jp"`
}

// CatalogMetaV1 defines model for CatalogMetaV1.
type CatalogMetaV1 struct {
	DataVersion string `json:"dataVersion"`
	RequestId   string `json:"requestId"`
}

// CatalogOperationApplicabilityV1 defines model for CatalogOperationApplicabilityV1.
type CatalogOperationApplicabilityV1 struct {
	union json.RawMessage
}

// CatalogOperationApplicabilityV10 defines model for CatalogOperationApplicabilityV1.0.
type CatalogOperationApplicabilityV10 struct {
	Operation CatalogOperationApplicabilityV10Operation `json:"operation"`
}

// CatalogOperationApplicabilityV10Operation defines model for CatalogOperationApplicabilityV1.0.Operation.
type CatalogOperationApplicabilityV10Operation string

// CatalogOperationApplicabilityV11 defines model for CatalogOperationApplicabilityV1.1.
type CatalogOperationApplicabilityV11 struct {
	Operation interface{}        `json:"operation"`
	Sections  []CatalogSectionV1 `json:"sections"`
}

// CatalogPositionCapabilityNameV1 defines model for CatalogPositionCapabilityNameV1.
type CatalogPositionCapabilityNameV1 string

// CatalogPositionV1 defines model for CatalogPositionV1.
type CatalogPositionV1 struct {
	union json.RawMessage
}

// CatalogRootSortCapabilityV1 defines model for CatalogRootSortCapabilityV1.
type CatalogRootSortCapabilityV1 struct {
	Field               CatalogRootSortCapabilityV1Field     `json:"field"`
	Operation           CatalogRootSortCapabilityV1Operation `json:"operation"`
	RequiresMergeSeries bool                                 `json:"requiresMergeSeries"`
	Scopes              []CatalogScopeV1                     `json:"scopes"`
	SubjectTypes        []CatalogSubjectTypeKeyV1            `json:"subjectTypes"`
}

// CatalogRootSortCapabilityV1Field defines model for CatalogRootSortCapabilityV1.Field.
type CatalogRootSortCapabilityV1Field string

// CatalogRootSortCapabilityV1Operation defines model for CatalogRootSortCapabilityV1.Operation.
type CatalogRootSortCapabilityV1Operation string

// CatalogScopeV1 defines model for CatalogScopeV1.
type CatalogScopeV1 string

// CatalogSectionSortCapabilityV1 defines model for CatalogSectionSortCapabilityV1.
type CatalogSectionSortCapabilityV1 struct {
	Field               CatalogSectionSortCapabilityV1Field `json:"field"`
	Operation           interface{}                         `json:"operation"`
	RequiresMergeSeries bool                                `json:"requiresMergeSeries"`
	Scopes              []CatalogScopeV1                    `json:"scopes"`
	Section             CatalogSectionV1                    `json:"section"`
	SubjectTypes        []CatalogSubjectTypeKeyV1           `json:"subjectTypes"`
}

// CatalogSectionSortCapabilityV1Field defines model for CatalogSectionSortCapabilityV1.Field.
type CatalogSectionSortCapabilityV1Field string

// CatalogSectionV1 defines model for CatalogSectionV1.
type CatalogSectionV1 string

// CatalogSelectionRuleV1 defines model for CatalogSelectionRuleV1.
type CatalogSelectionRuleV1 struct {
	Key         string                     `json:"key"`
	Kind        CatalogSelectionRuleV1Kind `json:"kind"`
	PositionKey string                     `json:"positionKey"`
	Value       string                     `json:"value"`
}

// CatalogSelectionRuleV1Kind defines model for CatalogSelectionRuleV1.Kind.
type CatalogSelectionRuleV1Kind string

// CatalogSortCapabilityV1 defines model for CatalogSortCapabilityV1.
type CatalogSortCapabilityV1 struct {
	union json.RawMessage
}

// CatalogStaffPositionV1 defines model for CatalogStaffPositionV1.
type CatalogStaffPositionV1 struct {
	Capabilities []CatalogPositionCapabilityNameV1 `json:"capabilities"`
	Categories   []string                          `json:"categories"`
	DisplayOrder int                               `json:"displayOrder"`
	Key          string                            `json:"key"`
	Kind         interface{}                       `json:"kind"`
	Label        string                            `json:"label"`
	Names        CatalogLocalizedNamesV1           `json:"names"`
	PositionId   int                               `json:"positionId"`
	Status       CatalogStaffPositionV1Status      `json:"status"`
	SubjectType  CatalogSubjectTypeKeyV1           `json:"subjectType"`
}

// CatalogStaffPositionV1Status defines model for CatalogStaffPositionV1.Status.
type CatalogStaffPositionV1Status string

// CatalogStaffSetPositionV1 defines model for CatalogStaffSetPositionV1.
type CatalogStaffSetPositionV1 struct {
	Capabilities []CatalogPositionCapabilityNameV1 `json:"capabilities"`
	Categories   []string                          `json:"categories"`
	DisplayOrder int                               `json:"displayOrder"`
	Key          string                            `json:"key"`
	Kind         interface{}                       `json:"kind"`
	Label        string                            `json:"label"`
	MemberKeys   []string                          `json:"memberKeys"`
	Names        CatalogLocalizedNamesV1           `json:"names"`
	Status       CatalogStaffSetPositionV1Status   `json:"status"`
	SubjectType  CatalogSubjectTypeKeyV1           `json:"subjectType"`
}

// CatalogStaffSetPositionV1Status defines model for CatalogStaffSetPositionV1.Status.
type CatalogStaffSetPositionV1Status string

// CatalogSubjectTypeKeyV1 defines model for CatalogSubjectTypeKeyV1.
type CatalogSubjectTypeKeyV1 string

// CatalogSubjectTypeV1 defines model for CatalogSubjectTypeV1.
type CatalogSubjectTypeV1 struct {
	Key   CatalogSubjectTypeKeyV1 `json:"key"`
	Label string                  `json:"label"`
}

// CatalogSuccessEnvelopeV1 defines model for CatalogSuccessEnvelopeV1.
type CatalogSuccessEnvelopeV1 struct {
	Data CatalogDataV1 `json:"data"`
	Meta CatalogMetaV1 `json:"meta"`
}

// AsCatalogOperationApplicabilityV10 returns the union data inside the CatalogOperationApplicabilityV1 as a CatalogOperationApplicabilityV10
func (t CatalogOperationApplicabilityV1) AsCatalogOperationApplicabilityV10() (CatalogOperationApplicabilityV10, error) {
	var body CatalogOperationApplicabilityV10
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCatalogOperationApplicabilityV10 overwrites any union data inside the CatalogOperationApplicabilityV1 as the provided CatalogOperationApplicabilityV10
func (t *CatalogOperationApplicabilityV1) FromCatalogOperationApplicabilityV10(v CatalogOperationApplicabilityV10) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCatalogOperationApplicabilityV10 performs a merge with any union data inside the CatalogOperationApplicabilityV1, using the provided CatalogOperationApplicabilityV10
func (t *CatalogOperationApplicabilityV1) MergeCatalogOperationApplicabilityV10(v CatalogOperationApplicabilityV10) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCatalogOperationApplicabilityV11 returns the union data inside the CatalogOperationApplicabilityV1 as a CatalogOperationApplicabilityV11
func (t CatalogOperationApplicabilityV1) AsCatalogOperationApplicabilityV11() (CatalogOperationApplicabilityV11, error) {
	var body CatalogOperationApplicabilityV11
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCatalogOperationApplicabilityV11 overwrites any union data inside the CatalogOperationApplicabilityV1 as the provided CatalogOperationApplicabilityV11
func (t *CatalogOperationApplicabilityV1) FromCatalogOperationApplicabilityV11(v CatalogOperationApplicabilityV11) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCatalogOperationApplicabilityV11 performs a merge with any union data inside the CatalogOperationApplicabilityV1, using the provided CatalogOperationApplicabilityV11
func (t *CatalogOperationApplicabilityV1) MergeCatalogOperationApplicabilityV11(v CatalogOperationApplicabilityV11) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CatalogOperationApplicabilityV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CatalogOperationApplicabilityV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCatalogStaffPositionV1 returns the union data inside the CatalogPositionV1 as a CatalogStaffPositionV1
func (t CatalogPositionV1) AsCatalogStaffPositionV1() (CatalogStaffPositionV1, error) {
	var body CatalogStaffPositionV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCatalogStaffPositionV1 overwrites any union data inside the CatalogPositionV1 as the provided CatalogStaffPositionV1
func (t *CatalogPositionV1) FromCatalogStaffPositionV1(v CatalogStaffPositionV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"staff"}`))
	t.union = b
	return err
}

// MergeCatalogStaffPositionV1 performs a merge with any union data inside the CatalogPositionV1, using the provided CatalogStaffPositionV1
func (t *CatalogPositionV1) MergeCatalogStaffPositionV1(v CatalogStaffPositionV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"staff"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCatalogCastPositionV1 returns the union data inside the CatalogPositionV1 as a CatalogCastPositionV1
func (t CatalogPositionV1) AsCatalogCastPositionV1() (CatalogCastPositionV1, error) {
	var body CatalogCastPositionV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCatalogCastPositionV1 overwrites any union data inside the CatalogPositionV1 as the provided CatalogCastPositionV1
func (t *CatalogPositionV1) FromCatalogCastPositionV1(v CatalogCastPositionV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"cast"}`))
	t.union = b
	return err
}

// MergeCatalogCastPositionV1 performs a merge with any union data inside the CatalogPositionV1, using the provided CatalogCastPositionV1
func (t *CatalogPositionV1) MergeCatalogCastPositionV1(v CatalogCastPositionV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"cast"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCatalogStaffSetPositionV1 returns the union data inside the CatalogPositionV1 as a CatalogStaffSetPositionV1
func (t CatalogPositionV1) AsCatalogStaffSetPositionV1() (CatalogStaffSetPositionV1, error) {
	var body CatalogStaffSetPositionV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCatalogStaffSetPositionV1 overwrites any union data inside the CatalogPositionV1 as the provided CatalogStaffSetPositionV1
func (t *CatalogPositionV1) FromCatalogStaffSetPositionV1(v CatalogStaffSetPositionV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"staffSet"}`))
	t.union = b
	return err
}

// MergeCatalogStaffSetPositionV1 performs a merge with any union data inside the CatalogPositionV1, using the provided CatalogStaffSetPositionV1
func (t *CatalogPositionV1) MergeCatalogStaffSetPositionV1(v CatalogStaffSetPositionV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"staffSet"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CatalogPositionV1) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CatalogPositionV1) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cast":
		return t.AsCatalogCastPositionV1()
	case "staff":
		return t.AsCatalogStaffPositionV1()
	case "staffSet":
		return t.AsCatalogStaffSetPositionV1()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CatalogPositionV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CatalogPositionV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCatalogRootSortCapabilityV1 returns the union data inside the CatalogSortCapabilityV1 as a CatalogRootSortCapabilityV1
func (t CatalogSortCapabilityV1) AsCatalogRootSortCapabilityV1() (CatalogRootSortCapabilityV1, error) {
	var body CatalogRootSortCapabilityV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCatalogRootSortCapabilityV1 overwrites any union data inside the CatalogSortCapabilityV1 as the provided CatalogRootSortCapabilityV1
func (t *CatalogSortCapabilityV1) FromCatalogRootSortCapabilityV1(v CatalogRootSortCapabilityV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCatalogRootSortCapabilityV1 performs a merge with any union data inside the CatalogSortCapabilityV1, using the provided CatalogRootSortCapabilityV1
func (t *CatalogSortCapabilityV1) MergeCatalogRootSortCapabilityV1(v CatalogRootSortCapabilityV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCatalogSectionSortCapabilityV1 returns the union data inside the CatalogSortCapabilityV1 as a CatalogSectionSortCapabilityV1
func (t CatalogSortCapabilityV1) AsCatalogSectionSortCapabilityV1() (CatalogSectionSortCapabilityV1, error) {
	var body CatalogSectionSortCapabilityV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCatalogSectionSortCapabilityV1 overwrites any union data inside the CatalogSortCapabilityV1 as the provided CatalogSectionSortCapabilityV1
func (t *CatalogSortCapabilityV1) FromCatalogSectionSortCapabilityV1(v CatalogSectionSortCapabilityV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCatalogSectionSortCapabilityV1 performs a merge with any union data inside the CatalogSortCapabilityV1, using the provided CatalogSectionSortCapabilityV1
func (t *CatalogSortCapabilityV1) MergeCatalogSectionSortCapabilityV1(v CatalogSectionSortCapabilityV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CatalogSortCapabilityV1) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"operation"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CatalogSortCapabilityV1) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "candidates":
		return t.AsCatalogRootSortCapabilityV1()
	case "coStar":
		return t.AsCatalogRootSortCapabilityV1()
	case "partners":
		return t.AsCatalogRootSortCapabilityV1()
	case "personDetail":
		return t.AsCatalogSectionSortCapabilityV1()
	case "rankings":
		return t.AsCatalogRootSortCapabilityV1()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CatalogSortCapabilityV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CatalogSortCapabilityV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
