[main]
appName = "BangumiStaffStats"
host = "0.0.0.0"
port = 5000

[http]
timeout = 10
retryWaitTime = 2
maxRetries = 3
userAgent = "AcuL/BangumiStaffStatistics/1.1 (Web) (https://github.com/AcuLY/BangumiStaffStats)"
accessToken = "YOUR_TOKEN"
rateLimit = 5
burst = 10 

[sqlite]
path = "./data/bgmss.sqlite"
maxOpenConnection = 8
maxIdleConnection = 4
maxLifetime = 30

[cache]
maxEntries = 1024

    [cache.ttl]
    collection = 24
    subject = 168
    sequel = 168
    person = 168
    credit = 168
    character = 168
    cast = 168
    statistic = 10

[bloom]
falsePositive = 0.001

[log]
appLogPath = "./logs/app/"
ginLogPath = "./logs/gin/"
gormLogPath = "./logs/gorm/"

