global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: bgmss-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]
