FROM python:3.10

COPY requirements.txt .
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

WORKDIR /scripts

COPY ./scripts/*.py ./

CMD ["python", "-u", "fetch_latest_jsonlines.py"]