services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bgmss-backend:latest
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
      - REDIS_ADDR=redis:${REDIS_PORT}
    networks:
      - bgmss
    volumes:
      - ./logs:/app/logs
      - ./config.toml:/app/config.toml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./static:/static
    networks:
      - bgmss

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --database=$$MYSQL_DATABASE -e 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - bgmss

  redis:
    image: redis:7.2
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 1024mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - redis-data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - bgmss

volumes:
  mysql-data:
  redis-data:

networks:
  bgmss: {}
