services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bgmss-backend:latest
    restart: unless-stopped
    ports:
      - "${APP_PORT}:5000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - ./data:/app/data:ro

  loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    image: bgmss-loader:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./jsonlines:/jsonlines
      - ./data:/data
      - ./scripts:/scripts
