FROM python:3.10

COPY requirements.txt .
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

COPY config.toml .
COPY update_database.py .
COPY fetch_latest_jsonlines.py .

CMD [ "python", "-u", "fetch_latest_jsonlines.py" ]