services:
  updater:
    environment:
      BGMSS_HTTPS_PROXY: ${BGMSS_UPDATER_HTTPS_PROXY}
    networks:
      - backend
      - updater_proxy

networks:
  updater_proxy:
    name: ${BGMSS_UPDATER_PROXY_NETWORK}
    external: true
