// 条目类型表
export const subjectTypeOptions = [
    { "label": '动画', "value": 2 },
    { "label": '书籍', "value": 1 },
    { "label": '游戏', "value": 4 },
    { "label": '音乐', "value": 3 },
    { "label": '影视', "value": 6 }
];

// 职位表
export const positionOptions = [
    // 0 占位
    [],
    // 1 书籍
    [
        { "label": "作者", "value": "作者" },
        { "label": "出版社", "value": "出版社" },
        { "label": "连载杂志", "value": "连载杂志" },
        { "label": "文库", "value": "文库" },
        { "label": "插图", "value": "插图" },
        { "label": "人物原案", "value": "人物原案" },
        { "label": "脚本", "value": "脚本" },
        { "label": "原作", "value": "原作" },
    ],
    // 2 动画
    [   
        { "label": "声优（仅主役）", "value": "声优（仅主役）" },
        { "label": "声优", "value": "声优" },
        { "label": "监督", "value": "导演" },
        { "label": "总监督", "value": "总导演" },
        { "label": "副监督", "value": "副导演" },
        { "label": "制作公司", "value": "动画制作" },
        { "label": "制片人", "value": "制片人" },
        { "label": "动画制片人", "value": "动画制片人" },
        { "label": "执行制片人", "value": "执行制片人" },
        { "label": "原作", "value": "原作" },
        { "label": "系列构成", "value": "系列构成" },
        { "label": "脚本", "value": "脚本" },
        { "label": "演出", "value": "演出" },
        { "label": "分镜", "value": "分镜" },
        { "label": "总作画监督", "value": "总作画监督" },
        { "label": "作画监督", "value": "作画监督" },
        { "label": "原案", "value": "原案" },
        { "label": "人物设定", "value": "人物设定" },
        { "label": "人物原案", "value": "人物原案" },
        { "label": "摄影监督", "value": "摄影监督" },
        { "label": "摄影", "value": "摄影" },
        { "label": "美术监督", "value": "美术监督" },
        { "label": "美术", "value": "背景美术" },
        { "label": "美术设计", "value": "美术设计" },
        { "label": "音乐", "value": "音乐" },
        { "label": "音响监督", "value": "音响监督" },
        { "label": "音效", "value": "音效" },
        { "label": "录音", "value": "录音" },
        { "label": "原画", "value": "原画" },
        { "label": "第二原画", "value": "第二原画" },
        { "label": "中割", "value": "补间动画" },
        { "label": "色彩设计", "value": "色彩设计" },
        { "label": "色指定", "value": "色彩指定" },
        { "label": "CG 导演", "value": "CG 导演" },
        { "label": "3DCG", "value": "3DCG" },
        { "label": "特效", "value": "特效" },
        { "label": "构图", "value": "构图" },
        { "label": "道具设计", "value": "道具设计" },
        { "label": "机械设定", "value": "机械设定" },
        { "label": "监修", "value": "监修" },
        { "label": "剪辑", "value": "剪辑" },
        { "label": "制作进行", "value": "制作管理" },
    ],
    // 3 音乐
    [
        { "label": "艺术家", "value": "艺术家" },
        { "label": "作曲", "value": "作曲" },
        { "label": "编曲", "value": "编曲" },
        { "label": "作词", "value": "作词" },
        { "label": "厂牌", "value": "厂牌" },
        { "label": "原作", "value": "原作" },
        { "label": "录音", "value": "录音" },
        { "label": "插图", "value": "插图" },
        { "label": "脚本（广播剧）", "value": "脚本" },
        { "label": "制作人", "value": "制作人" },
        { "label": "出版方", "value": "出版方" },
        { "label": "乐器", "value": "乐器" },
        { "label": "声乐", "value": "声乐" },
        { "label": "母带", "value": "母带制作" },
        { "label": "混音", "value": "混音" },
    ],
    // 4 游戏
    [
        { "label": "声优（仅主役）", "value": "声优（仅主役）" },
        { "label": "声优", "value": "声优" },
        { "label": "开发", "value": "开发" },
        { "label": "发行", "value": "发行" },
        { "label": "游戏设计师", "value": "游戏设计师" },
        { "label": "剧本", "value": "剧本" },
        { "label": "美工", "value": "美工" },
        { "label": "音乐", "value": "音乐" },
        { "label": "关卡设计", "value": "关卡设计" },
        { "label": "人物设定", "value": "人物设定" },
        { "label": "原画", "value": "原画" },
        { "label": "动画制作", "value": "动画制作" },
        { "label": "原作", "value": "原作" },
        { "label": "导演", "value": "导演" },
        { "label": "动画监督", "value": "动画监督" },
        { "label": "制作总指挥", "value": "制作总指挥" },
        { "label": "程序", "value": "程序" },
        { "label": "SD原画", "value": "SD原画" },
        { "label": "背景", "value": "背景" },
        { "label": "监修", "value": "监修" },
        { "label": "企画", "value": "企画" },
        { "label": "制作人", "value": "制作人" }
    ],
    // 5 无
    [],
    // 6 三次元
    [
        { "label": "原作", "value": "原作" },
        { "label": "导演", "value": "导演" },
        { "label": "编剧", "value": "编剧" },
        { "label": "音乐", "value": "音乐" },
        { "label": "执行制片人", "value": "执行制片人" },
        { "label": "制片人/制作人", "value": "制片人/制作人" },
        { "label": "监制", "value": "监制" },
        { "label": "剪辑", "value": "剪辑" },
        { "label": "摄影", "value": "摄影" },
        { "label": "主演", "value": "主演" },
        { "label": "配角", "value": "配角" },
        { "label": "制作", "value": "制作" },
        { "label": "出品", "value": "出品" }
    ],
    
];