import { SUBJECT_TYPE } from '@/constants/types'

// 条目类型表
export const SUBJECT_TYPE_OPTIONS = [
	{ label: '动画', value: SUBJECT_TYPE.ANIME },
	{ label: '书籍', value: SUBJECT_TYPE.BOOK },
	{ label: '游戏', value: SUBJECT_TYPE.GAME },
	{ label: '音乐', value: SUBJECT_TYPE.MUSIC },
	{ label: '影视', value: SUBJECT_TYPE.REAL },
]

// 职位表
export const POSITION_OPTIONS = {
	[SUBJECT_TYPE.BOOK]: [
		{ label: '作者', value: '作者' },
		{ label: '出版社', value: '出版社' },
		{ label: '连载杂志', value: '连载杂志' },
		{ label: '文库', value: '文库' },
		{ label: '插图', value: '插图' },
		{ label: '人物原案', value: '人物原案' },
		{ label: '脚本', value: '脚本' },
		{ label: '原作', value: '原作' },
		{ label: '作画', value: '作画' },
		{ label: '译者', value: '译者' },
		{ label: '客串', value: '客串' },
		{ label: '出品方', value: '出品方' },
		{ label: '文库品牌', value: '文库品牌' },
	],

	[SUBJECT_TYPE.ANIME]: [
		{ label: '声优（仅主役）', value: '声优（仅主役）' },
		{ label: '声优', value: '声优' },
		{ label: '监督', value: '导演' },
		{ label: '总监督', value: '总导演' },
		{ label: '副监督', value: '副导演' },
		{ label: '制作公司', value: '动画制作' },
		{ label: '制片人', value: '制片人' },
		{ label: '总制片人', value: '总制片人' },
		{ label: '动画制片人', value: '动画制片人' },
		{ label: '执行制片人', value: '执行制片人' },
		{ label: '原作', value: '原作' },
		{ label: '系列构成', value: '系列构成' },
		{ label: '脚本', value: '脚本' },
		{ label: '演出', value: '演出' },
		{ label: '分镜', value: '分镜' },
		{ label: '总作画监督', value: '总作画监督' },
		{ label: '作画监督', value: '作画监督' },
		{ label: '原案', value: '原案' },
		{ label: '人物设定', value: '人物设定' },
		{ label: '人物原案', value: '人物原案' },
		{ label: '摄影监督', value: '摄影监督' },
		{ label: '摄影', value: '摄影' },
		{ label: '美术监督', value: '美术监督' },
		{ label: '美术', value: '背景美术' },
		{ label: '美术设计', value: '美术设计' },
		{ label: '音乐', value: '音乐' },
		{ label: '音响监督', value: '音响监督' },
		{ label: '音效', value: '音效' },
		{ label: '录音', value: '录音' },
		{ label: '原画', value: '原画' },
		{ label: '第二原画', value: '第二原画' },
		{ label: '中割', value: '补间动画' },
		{ label: '动画检查', value: '动画检查' },
		{ label: '色彩设计', value: '色彩设计' },
		{ label: '色指定', value: '色彩指定' },
		{ label: 'CG 导演', value: 'CG 导演' },
		{ label: '3D 监督', value: '3D 监督' },
		{ label: '3DCG', value: '3DCG' },
		{ label: '特效', value: '特效' },
		{ label: '构图', value: '构图' },
		{ label: '道具设计', value: '道具设计' },
		{ label: '机械设定', value: '机械设定' },
		{ label: '监修', value: '监修' },
		{ label: '剪辑', value: '剪辑' },
		{ label: '制作进行', value: '制作进行' },
		{ label: '制作管理', value: '制作管理' },
		{ label: '设定制作', value: '设定制作' },
		{ label: '动作作画监督', value: '动作作画监督' },
		{ label: '机械作画监督', value: '机械作画监督' },
		{ label: '特效作画监督', value: '特效作画监督' },
		{ label: '演员监督', value: '演员监督' },
		{ label: '配音监督', value: '配音监督' },
		{ label: '系列监督', value: '系列监督' },
		{ label: '主演出', value: '主演出' },
		{ label: '主动画师', value: '主动画师' },
		{ label: 'OP·ED 分镜', value: 'OP·ED 分镜' },
		{ label: '音乐制作人', value: '音乐制作人' },
		{ label: '主题歌编曲', value: '主题歌编曲' },
		{ label: '主题歌作曲', value: '主题歌作曲' },
		{ label: '主题歌作词', value: '主题歌作词' },
		{ label: '主题歌演出', value: '主题歌演出' },
		{ label: '插入歌演出', value: '插入歌演出' },
		{ label: '企划', value: '企划' },
		{ label: '企划制作人', value: '企划制作人' },
		{ label: '制作', value: '制作' },
		{ label: '宣传', value: '宣传' },
		{ label: '联合导演', value: '联合导演' },
		{ label: '数码绘图', value: '数码绘图' },
		{ label: '联合制片人', value: '联合制片人' },
		{ label: '制作协调', value: '制作协调' },
		{ label: '监制', value: '监制' },
		{ label: '厂牌', value: '厂牌' },
		{ label: '音响', value: '音响' },
		{ label: '台词编辑', value: '台词编辑' },
		{ label: '助理制片人', value: '助理制片人' },
		{ label: '后期制片协调', value: '后期制片协调' },
		{ label: '制作助理', value: '制作助理' },
		{ label: '作画监督助理', value: '作画监督助理' },
		{ label: '音乐助理', value: '音乐助理' },
		{ label: '演出助理', value: '演出助理' },
		{ label: '录音助理', value: '录音助理' },
		{ label: '设定', value: '设定' },
		{ label: '背景设定', value: '背景设定' },
		{ label: '制作协力', value: '制作协力' },
		{ label: '协力', value: '协力' },
		{ label: '制作进行协力', value: '制作进行协力' },
		{ label: '特别鸣谢', value: '特别鸣谢' },
	],

	[SUBJECT_TYPE.MUSIC]: [
		{ label: '艺术家', value: '艺术家' },
		{ label: '作曲', value: '作曲' },
		{ label: '编曲', value: '编曲' },
		{ label: '作词', value: '作词' },
		{ label: '厂牌', value: '厂牌' },
		{ label: '原作', value: '原作' },
		{ label: '录音', value: '录音' },
		{ label: '插图', value: '插图' },
		{ label: '脚本（广播剧）', value: '脚本' },
		{ label: '制作人', value: '制作人' },
		{ label: '出版方', value: '出版方' },
		{ label: '乐器', value: '乐器' },
		{ label: '声乐', value: '声乐' },
		{ label: '母带', value: '母带制作' },
		{ label: '混音', value: '混音' },
	],

	[SUBJECT_TYPE.GAME]: [
		{ label: '声优（仅主役）', value: '声优（仅主役）' },
		{ label: '声优', value: '声优' },
		{ label: '开发', value: '开发' },
		{ label: '发行', value: '发行' },
		{ label: '游戏设计师', value: '游戏设计师' },
		{ label: '剧本', value: '剧本' },
		{ label: '美工', value: '美工' },
		{ label: '音乐', value: '音乐' },
		{ label: '关卡设计', value: '关卡设计' },
		{ label: '人物设定', value: '人物设定' },
		{ label: '原画', value: '原画' },
		{ label: '动画制作', value: '动画制作' },
		{ label: '原作', value: '原作' },
		{ label: '导演', value: '导演' },
		{ label: '动画监督', value: '动画监督' },
		{ label: '制作总指挥', value: '制作总指挥' },
		{ label: '程序', value: '程序' },
		{ label: 'SD 原画', value: 'SD 原画' },
		{ label: '背景', value: '背景' },
		{ label: '监修', value: '监修' },
		{ label: '企画', value: '企画' },
		{ label: '制作人', value: '制作人' },
		{ label: '主题歌作曲', value: '主题歌作曲' },
		{ label: '主题歌作词', value: '主题歌作词' },
		{ label: '主题歌演出', value: '主题歌演出' },
		{ label: '插入歌演出', value: '插入歌演出' },
		{ label: 'QC', value: 'QC' },
		{ label: '动画剧本', value: '动画剧本' },
		{ label: '协力', value: '协力' },
		{ label: 'CG 监修', value: 'CG 监修' },
		{ label: '系列构成', value: '系列构成' },
		{ label: '机械设定', value: '机械设定' },
		{ label: '音响监督', value: '音响监督' },
		{ label: '作画监督', value: '作画监督' },
	],

	// 三次元
	[SUBJECT_TYPE.REAL]: [
		{ label: '原作', value: '原作' },
		{ label: '导演', value: '导演' },
		{ label: '编剧', value: '编剧' },
		{ label: '音乐', value: '音乐' },
		{ label: '执行制片人', value: '执行制片人' },
		{ label: '制片人/制作人', value: '制片人/制作人' },
		{ label: '监制', value: '监制' },
		{ label: '剪辑', value: '剪辑' },
		{ label: '摄影', value: '摄影' },
		{ label: '主演', value: '主演' },
		{ label: '配角', value: '配角' },
		{ label: '制作', value: '制作' },
		{ label: '出品', value: '出品' },
		{ label: '共同执行制作', value: '共同执行制作' },
		{ label: '副制作人/执行顾问', value: '副制作人/执行顾问' },
		{ label: '故事', value: '故事' },
		{ label: '编审', value: '编审' },
		{ label: '创意总监', value: '创意总监' },
		{ label: '主题歌演出', value: '主题歌演出' },
	],
}
