import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const readWorkbenchFile = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

const appSource = readWorkbenchFile('../WorkbenchApp.vue')
const queryWorkspaceSource = readWorkbenchFile('./QueryWorkspace.vue')
const mobilePickerSource = readWorkbenchFile('./QueryMobilePickerSkeleton.vue')
const rankingSource = readWorkbenchFile('./RankingQuerySkeleton.vue')
const coStarSource = readWorkbenchFile('./CoStarQuerySkeleton.vue')
const preferenceSource = readWorkbenchFile('./QueryPreferenceSkeleton.vue')
const tagSource = readWorkbenchFile('./QueryTagSummarySkeleton.vue')
const workBrowserSource = readWorkbenchFile('./QueryWorkBrowserSkeleton.vue')
const skeletonStyles = readWorkbenchFile('../styles/modules/query-skeleton.css')
const subjectWorkStyles = readWorkbenchFile('../styles/modules/subject-work-list.css')
const participantStyles = readWorkbenchFile('../styles/modules/shared-work-participants.css')
const themeSource = readWorkbenchFile('../naiveThemeOverrides.ts')

describe('query skeleton production parity', () => {
	it('uses the real query-loading branch and reserves the co-star mobile picker row', () => {
		expect(appSource).toMatch(/<RankingQuerySkeleton\s+v-else-if="workbench\.queryLoading\.value && workbench\.mode\.value === 'ranking'"/)
		expect(appSource).toMatch(/<CoStarQuerySkeleton\s+v-else-if="workbench\.queryLoading\.value && workbench\.mode\.value === 'co-star'"/)
		expect(appSource).toMatch(/<QueryMobilePickerSkeleton[\s\S]*?v-if="!loading && !error && workbench\.queryLoading\.value && workbench\.mode\.value === 'co-star'"/)
		expect(appSource).toContain('v-else-if="!loading && !error')
		expect(mobilePickerSource).toContain('class="mobile-picker-entry header-edit-card query-skeleton query-skeleton__mobile-picker-entry"')
		expect(mobilePickerSource).toContain('class="mobile-picker-entry__action header-edit-card__action"')
		expect(queryWorkspaceSource).toMatch(/const accepted = workbench\.applyQuery\(\)[\s\S]*?workbench\.queryEditing\.value = false/)
		expect(queryWorkspaceSource).toContain('? draftQuerySummaryParts.value')
		expect(queryWorkspaceSource).toContain('const draftQuerySummaryParts = computed(() => querySummaryPartsFor(workbench.queryDraft))')
		expect(queryWorkspaceSource).toContain("'查询中，打开查询面板以取消'")
	})

	it('does not retain the temporary hash-preview route', () => {
		expect(appSource).not.toContain('skeletonPreviewMode')
		expect(appSource).not.toContain('skeletonPreviewRoute')
		expect(appSource).not.toContain('hashchange')
		expect(appSource).not.toContain('#/skeleton/')
	})

	it('uses the real two-column participant topology and responsive container rules', () => {
		expect(workBrowserSource).toContain('const participantRows = [[0, 1], [2]]')
		expect(coStarSource).toContain('class="analysis-section shared-works-section query-skeleton__works-section"')
		expect(workBrowserSource).toContain('class="shared-work-participants query-skeleton__participants"')
		expect(workBrowserSource).toContain('class="subject-work-row person-work-row query-skeleton__subject-work-row"')
		expect(workBrowserSource).toContain('class="shared-work-participant-row"')
		expect(workBrowserSource).toContain('class="shared-work-participant"')
		expect(workBrowserSource).toContain('width="20px" height="20px" round')
		expect(workBrowserSource).not.toContain('query-skeleton__participant-row')
		expect(subjectWorkStyles).toMatch(/@container shared-works-section \(min-width: 840px\)\s*\{[^}]*\.person-work-list:not\(\.subject-work-list--compact\)\s*\{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/s)
		expect(participantStyles).toMatch(/@container subject-work-row \(max-width: 480px\)\s*\{[^}]*\.shared-work-participant-row\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\);/s)
	})

	it('lets media wrappers own their production corner shape', () => {
		expect(rankingSource).toMatch(/person-row__avatar[\s\S]*?height="100%" sharp/)
		expect(rankingSource).toMatch(/person-profile__portrait[\s\S]*?height="100%" sharp/)
		expect(rankingSource).toMatch(/query-skeleton__score-fill[\s\S]*?height="100%" sharp/)
		expect(coStarSource).toMatch(/candidate-row__portrait[\s\S]*?height="100%" sharp/)
		expect(preferenceSource).toContain('class="safe-image safe-image--subject query-skeleton__preference-cover"')
		expect(workBrowserSource).toContain('class="subject-work-row__cover safe-image safe-image--subject query-skeleton__subject-cover"')
		expect(themeSource).toContain("borderRadius: 'min(var(--query-skeleton-radius-cap, 6px), var(--query-skeleton-radius-ratio, 20%))'")
	})

	it('matches fixed control tracks and narrow-screen density', () => {
		expect(rankingSource).toContain("width=\"143px\" :height=\"isMobile ? '28px' : '34px'\"")
		expect(rankingSource).toContain("width=\"171px\" :height=\"isMobile ? '28px' : '34px'\"")
		expect(coStarSource).toContain("width=\"143px\" :height=\"compactViewport ? '28px' : '34px'\"")
		expect(coStarSource).toContain("width=\"171px\" :height=\"compactViewport ? '28px' : '34px'\"")
		expect(coStarSource).toContain('class="query-skeleton__checkbox"')
		expect(coStarSource).toContain(":width=\"item === 0 ? '60px' : item === 1 ? '79px' : '81px'\"")
		expect(skeletonStyles).toContain('grid-template-columns: minmax(0, 1fr) minmax(92px, 0.52fr) auto;')
		expect(skeletonStyles).toMatch(/\.query-skeleton__toolbar-order\s*\{[^}]*width:\s*76px;/s)
		expect(skeletonStyles).toMatch(/@media \(width < 780px\)[\s\S]*?\.query-skeleton__toolbar-order\s*\{[^}]*width:\s*68px;/s)
		expect(skeletonStyles).toMatch(/@media \(max-width: 520px\)[\s\S]*?\.query-skeleton__score-table-scroll\s*\{[^}]*height:\s*618px;/s)
		expect(skeletonStyles).toMatch(/@media \(max-width: 520px\)[\s\S]*?\.query-skeleton__matrix :is\(th, td\)\s*\{[^}]*height:\s*69px;/s)
		expect(skeletonStyles).toMatch(/@container query-skeleton-analysis \(max-width: 500px\)[\s\S]*?\.query-skeleton__matrix :is\(th, td\)\s*\{[^}]*height:\s*69px;/s)
		expect(skeletonStyles).toMatch(/@media \(max-width: 520px\)[\s\S]*?\.query-skeleton__rating-domain\s*\{[^}]*min-height:\s*0;/s)
	})

	it('uses the responsive neutral-pill tag height and the real preference copy rhythm', () => {
		expect(tagSource).toContain("const compactViewport = useMediaQuery('(max-width: 520px)')")
		expect(tagSource).toContain(":height=\"compactViewport ? '16px' : '12px'\"")
		expect(tagSource).toContain(":height=\"compactViewport ? '20px' : '28px'\"")
		expect(tagSource).toMatch(/:height="compactViewport \? '20px' : '28px'"[\s\S]*?round/)
		expect(workBrowserSource).toContain('height="var(--query-skeleton-meta-tag-height)"')
		expect(skeletonStyles).toContain('--query-skeleton-meta-tag-height: 20px;')
		expect(skeletonStyles).toMatch(/@container subject-work-list \(max-width: 480px\)[\s\S]*?--query-skeleton-meta-tag-height:\s*16px;/s)
		expect(preferenceSource).toContain("variant?: 'ranking' | 'shared'")
		expect(preferenceSource).toContain("props.variant === 'shared' && column === 0")
		expect(preferenceSource).toContain('class="muted-row query-skeleton__preference-empty"')
		expect(coStarSource).toContain('<QueryPreferenceSkeleton variant="shared" />')
		expect(rankingSource).toContain('<QueryPreferenceSkeleton variant="ranking" />')
		expect(skeletonStyles).toMatch(/\.query-skeleton__preference-copy\s*\{[^}]*gap:\s*2px;/s)
	})
})
